### ISSUE TITLE
Wrong files for 15.3

### ISSUE THREAD

**Issue by mramosch** [filsv/iOSDeviceSupport#121]
The 15.3 files are just a renamed copy of 15.2 and do not work for me. (same date and size!!!)

Could anybody upload the real 15.3 files please?

Thanks a lot in advance!

**Comment by franalt** [comment]
Can confirm its not working, my device is 15.3.1.

**Comment by lilingxi01** [comment]
Not working for me too. Device is 15.3.1 and XCode is 13.2.1.

**Comment by naimskaria** [comment]
Same issue i am also facing. renaming to 15.3.1 is not working

**Comment by dinterliche** [comment]
Same issue. 

IOS 15.3.1 (Device Im trying to DEBUG)
macOS Version 10.15.7 (Build 19H2)
Xcode 12.4 (17801) (Build 12D4e)

**Comment by jonasrotilli** [comment]
Same issue.

IOS 15.3.1
macOS Version 10.15.7
Xcode 12.2 (12B45b)

**Comment by schnausages** [comment]
Also having the issue with 15.3 support files as well:

iOS 15.3.1
XCode 12.4

Love the support filsv has provided with these files though! Probably a small mistake

**Comment by andreydos** [comment]
Works fine with 15.3

**Comment by franalt** [comment]
@filsv the 15.4 files are missing 404 not found

**Comment by filsv** [comment]
@franalt Its works for me, please try direct link - https://github.com/filsv/iPhoneOSDeviceSupport/raw/master/15.4.zip

**Comment by filsv** [comment]
@andreydos Most recently updated, check it out:
