### ISSUE TITLE
iOS 15.6 support file

### ISSUE THREAD

**Issue by Tang1705** [filsv/iOSDeviceSupport#128]
Xcode 13.4 is realized and include iOS 15.5, however, we need its support for iOS 15.6 to deploy app yo devices.

**Comment by weihaihan066078** [comment]
we need.

**Comment by Python3-8** [comment]
Uhh, I don't think that exists yet. 
![image](https://user-images.githubusercontent.com/66139317/171998065-3c2326c0-034f-4dd1-811a-4a1425f15056.png)

**Comment by Tang1705** [comment]
> Uhh, I don't think that exists yet.
> ![image](https://user-images.githubusercontent.com/66139317/171998065-3c2326c0-034f-4dd1-811a-4a1425f15056.png)

I can't update Xcode to support iOS 15.6. I also know that the latest version of Xcode just supports iOS 15.5. However, I have a iPad Pro which is updated to iOS 15.6. So I want to know if this work can help me?

**Comment by Python3-8** [comment]
> Uhh, I don't think that exists yet. ![image](https://user-images.githubusercontent.com/66139317/171998065-3c2326c0-034f-4dd1-811a-4a1425f15056.png)

Oh, wait, iPadOS 15.6 beta is out. Well, I guess you have to either look for a way to downgrade iPadOS or wait till Xcode 13.5 comes out.

**Comment by Tang1705** [comment]
Yep, you're right.

**Comment by Tang1705** [comment]
> > Uhh, I don't think that exists yet. ![image](https://user-images.githubusercontent.com/66139317/171998065-3c2326c0-034f-4dd1-811a-4a1425f15056.png)
> 
> Oh, wait, iPadOS 15.6 beta is out. Well, I guess you have to either look for a way to downgrade iPadOS or wait till Xcode 13.5 comes out.

After WWDC22, ipad can be upgraded to ios16. And, we can download xcode 14 to get support for ios15.5 and 16

**Comment by filsv** [comment]
@Tang1705 @weihaihan066078 @Python3-8 Here we go: [iOS 15.5](https://github.com/filsv/iOSDeviceSupport/raw/master/15.5.zip)

**Comment by yangyuanpeng** [comment]
您的邮件我已收到，我会尽快处理。谢谢。---杨远鹏
