### ISSUE TITLE
iOS 15.5 Support file for Xcode 12.1

### ISSUE THREAD

**Issue by Python3-8** [filsv/iOSDeviceSupport#129]
Where can I find the iOS 15.5 support file for Xcode 12.1? I just can't believe Apple, expecting us to buy new MacBooks every year.

**Comment by Python3-8** [comment]
By the way, my app uses Flutter, if that information is needed.

**Comment by chiragsrvstv** [comment]
> By the way, my app uses Flutter, if that information is needed. And if it's required then I can update Xcode 12.4.

Until support file for iOS15.5 is added as a workaround you can rename 14.4 to 14.5 and it should work :)

**Comment by filsv** [comment]
@Python3-8 @chiragsrvstv Here we go: [iOS 15.5](https://github.com/filsv/iOSDeviceSupport/raw/master/15.5.zip)
