### ISSUE TITLE
iOS 16

### ISSUE THREAD

**Issue by Derewith** [filsv/iOSDeviceSupport#130]
We need support for iOS 16 beta to deploy app in older xCode

**Comment by Tang1705** [comment]
> We need support for iOS 16 beta to deploy app in older xCode

you can download a Xcode beat which is also know as the Xcode 14 to get the support for iOS 16.

**Comment by filsv** [comment]
@Derewith @Tang1705  Here we go: [16.0](https://github.com/filsv/iOSDeviceSupport/raw/master/16.0.zip)
