### ISSUE TITLE
16.0 beta3 support?

### ISSUE THREAD

**Issue by jinfagang** [filsv/iOSDeviceSupport#140]
16.0 beta3 support?

**Comment by Grayson2019** [comment]
I have the same question. I tried but it seemed like not working. @jinfagang

**Comment by filsv** [comment]
@jinfagang @Grayson5317 Try to use Regular 16.0 - https://github.com/filsv/iOSDeviceSupport/blob/master/16.0.zip

**Comment by njajones** [comment]
+1 to the above issue. Tried using 16.0 but it wouldn't work. Recognises device and gets as far as installing, but then fails with a popup about "incompatibility"

**Comment by HiroshiOshiro** [comment]
Same issue. 

Even get support file from Xcode 14, getting this message
```
This operation can fail if the version of the OS on the device is incompatible with the installed version of Xcode. You may also need to restart your mac and device in order to correctly detect compatibility.
```

Has anyone succeeded to using iOS 16 device with Xcode 13.x?

**Comment by kbrin423** [comment]
Same for me:

Xcode 13.3.1
iOs 16.0

error after build succeed:
This operation can fail if the version of the OS on the device is incompatible with the installed version of Xcode. You may also need to restart your mac and device in order to correctly detect compatibility.

**Comment by sardineLee** [comment]
It looks like the DeveloperDiskImage in the 16.0.zip file in this git is different from the one in the actual Xcode 14. 

I copied the DeveloperDiskImage from Xcode 14 to my other Xcode 13.2 and this worked.

**Comment by filsv** [comment]
@njajones @HiroshiOshiro @kbrin423 @sardineLee Guys, I'm using Xcode 14.2 (14C18) + iOS 16.4, works great for me, Try to use 16.1 instead ([Download link](https://github.com/filsv/iOSDeviceSupport/raw/master/16.1.zip)), hope it will help, let's me know if not.
