### ISSUE TITLE
iOS 15.7 support?

### ISSUE THREAD

**Issue by gezihuzi** [filsv/iOSDeviceSupport#144]
Apple has pushed out the official versions of iOS 15.7 and iOS 16.0 at the same time. Will iOS 15.7 be supported?

**Comment by wzc0003** [comment]
I have the same problem

**Comment by xygkevin** [comment]
I have the same problem

**Comment by hainuo** [comment]
I have the same problem

**Comment by gezihuzi** [comment]
> Try to use 15.6 dmg

I have tried to use the 15.6 image, but after testing I still can't connect the device for debugging.

**Comment by zyflovelam** [comment]
Same problem, can't do anything now

**Comment by globules-io** [comment]
missing from 13.4.1 and 14

**Comment by zmGitHub** [comment]
+1

**Comment by wzc0003** [comment]
lol

**Comment by g-mocken** [comment]
For me, the combination Xcode 13.2.1 (on BigSur) works flawlessly with iOS/iPadOS 15.7 devices using ONLY the 15.5 image from Xcode 13.4. Installing any other image >15.5 from Xcode 14 results in errors, though.

**Comment by HackHarry** [comment]
Using 15.5 image works for me.

**Comment by ujeshpatel** [comment]
Xcode 14 cannot be used with iOS 15.7 for development. (99847608) 
Workaround: Use Xcode 13.4.1 with iOS 15.7.

Please read  [Xcode 14 Release Note ](https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes )

**Comment by biyu6** [comment]
> 使用 15.5 图像对我有用。

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport

**Comment by biyu6** [comment]
> works for me.

对我也有用！[抱拳]

**Comment by alexzh16** [comment]
you can download  Xcode 13.4.1 copy iOS 15.7 to Xcode 14, restart Xcode 14 and all will be worked. After coped, delete Xcode  13.4.1. Or find iOS 15.7 on another GitHub account.

**Comment by xygkevin** [comment]
> you can download Xcode 13.4.1 copy iOS 15.7 to Xcode 14, restart Xcode 14 and all will be worked. After coped, delete Xcode 13.4.1. Or find iOS 15.7 on another GitHub account.

可以提供一下 15.7 的文件吗？

**Comment by alexzh16** [comment]
> > you can download Xcode 13.4.1 copy iOS 15.7 to Xcode 14, restart Xcode 14 and all will be worked. After coped, delete Xcode 13.4.1. Or find iOS 15.7 on another GitHub account.
> 
> 可以提供一下 15.7 的文件吗？

https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes (Workaround: Use Xcode 13.4.1 with iOS 15.7. ). 

Im download from GitHub 15.7, than put to Xcode 14 and now my iPhone 6s with 15.7 working for development as before.

**Comment by rtrudel** [comment]
> > > you can download Xcode 13.4.1 copy iOS 15.7 to Xcode 14, restart Xcode 14 and all will be worked. After coped, delete > https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes (Workaround: Use Xcode 13.4.1 with iOS 15.7. ).
> 
> Im download from GitHub iOs [15.7](https://github.com/JinjunHan/iOSDeviceSupport), than put to Xcode 14 and now my iPhone 6s with 15.7 working for development as before.

This works for me! Thanks!

**Comment by gezihuzi** [comment]
> > > you can download Xcode 13.4.1 copy iOS 15.7 to Xcode 14, restart Xcode 14 and all will be worked. After coped, delete Xcode 13.4.1. Or find iOS 15.7 on another GitHub account.
> > 
> > 
> > 可以提供一下 15.7 的文件吗？
> 
> https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes (Workaround: Use Xcode 13.4.1 with iOS 15.7. ).
> 
> Im download from GitHub iOs [15.7](https://github.com/JinjunHan/iOSDeviceSupport), than put to Xcode 14 and now my iPhone 6s with 15.7 working for development as before.

Thanks!❤️

**Comment by mkll** [comment]
> For me, the combination Xcode 13.2.1 (on BigSur) works flawlessly with iOS/iPadOS 15.7 devices using ONLY the 15.5 image from Xcode 13.4. Installing any other image >15.5 from Xcode 14 results in errors, though.

Thanks! The combination of Xcode 13.2 (BigSur 11.4), device support 15.5, and iOS device 15.7.2 works great.

**Comment by rechiearnado21** [comment]
how to copy iOS 15.7 to Xcode 14 please help I'm new to xcode

**Comment by mkll** [comment]
@rechiearnado21 Xcode 14 supports iOS 15.7 out of the box. You don't have to do anything.
