### ISSUE TITLE
xcode version 13.2.1 and support file for ios 16 not worked?

### ISSUE THREAD

**Issue by aldybuanaa** [filsv/iOSDeviceSupport#146]
I'm on Xcode 13.2.1 , and I downloaded the support files for iOS 16.0
My physical device is iPhone XR with iOS 16.0 installed.

![Screenshot 2022-09-17 at 12 38 59](https://user-images.githubusercontent.com/44077752/190842305-3b001260-67c5-4259-a775-aa86db02236c.png)

**Comment by Curtis3007** [comment]
Change the downloaded folder from 16 to 16.0. I tried and it worked

**Comment by aldybuanaa** [comment]
> Change the downloaded folder from 16 to 16.0. I tried and it worked

the folder name is already 16.0 when I download it but still can't

**Comment by Curtis3007** [comment]
The last way, I think you need update your mac and update Xcode to the 14.0 version

**Comment by aldybuanaa** [comment]
> The last way, I think you need update your mac and update Xcode to the 14.0 version

sad, my mac is too old to update to the newest version🙁 I hope there's the other way

**Comment by Pavel-Laukhin** [comment]
@aldybuanaa I find the solution!

You need to open Settings on your iPhone, go to "Privacy & Security", and at the very bottom go to "Developer Mode" and turn it on :)

**Comment by aldybuanaa** [comment]
> @aldybuanaa I find the solution!
> 
> You need to open Settings on your iPhone, go to "Privacy & Security", and at the very bottom go to "Developer Mode" and turn it on :)

It works! thanks bro
note : but on some devices, it doesn't always appear the developer mode, and I found a video on youtube how to show up developer mode 
here is the link : [https://www.youtube.com/watch?v=pjOwtVS4jMA](url)

**Comment by PaulDFPV** [comment]
> > @aldybuanaa I find the solution!
> > You need to open Settings on your iPhone, go to "Privacy & Security", and at the very bottom go to "Developer Mode" and turn it on :)
> 
> It works! thanks bro note : but on some devices, it doesn't always appear the developer mode, and I found a video on youtube how to show up developer mode here is the link : https://www.youtube.com/watch?v=pjOwtVS4jMA

That video has been taken down. Do you happen to remember the steps? I'm having the issue with the missing developer mode toggle. iOS 16.2, xcode 13.2.1.

**Comment by PaulDFPV** [comment]
> > > @aldybuanaa I find the solution!
> > > You need to open Settings on your iPhone, go to "Privacy & Security", and at the very bottom go to "Developer Mode" and turn it on :)
> > 
> > 
> > It works! thanks bro note : but on some devices, it doesn't always appear the developer mode, and I found a video on youtube how to show up developer mode here is the link : https://www.youtube.com/watch?v=pjOwtVS4jMA
> 
> That video has been taken down. Do you happen to remember the steps? I'm having the issue with the missing developer mode toggle. iOS 16.2, xcode 13.2.1.

I got it working. I had to sideload an app to force the toggle to appear.
