### ISSUE TITLE
Update "About" to include iOS 16.0

### ISSUE THREAD

**Issue by NicolasCombe5555** [filsv/iOSDeviceSupport#148]
<img width="292" alt="Screen Shot 2022-09-21 at 17 46 17" src="https://user-images.githubusercontent.com/42418337/191623569-1839b9df-3886-4ea6-bf8b-3cc404738527.png">

It currently states:

> Xcode iPhoneOS DeviceSupport files (6.0 - 15.4)

**Comment by filsv** [comment]
@NicolasCombe5555 Thanks, updated!
