### ISSUE TITLE
Unable to reuse 16.0 files for iOS 16.0.2 (20A362) on Xcode version 13.4.1

### ISSUE THREAD

**Issue by tsiareshchankau** [filsv/iOSDeviceSupport#150]
The device is at iOS 16.0.2 (20A362)
Xcode version 13.4.1
Getting **Failed to prepare device for development.** when adding 16.0 files. 

Following this note, did not help. I've also tried `16.0 (20A362)`, `16.0.2 (20A362)`

> If you need upper version of the support files less than 1 iteration (eg. You have "15.0" and you need "15.1.5" - You can simply rename folder from "15.0" to "15.1.5" and it should work or try to use next iteration version of the support files, is exist "15.2", otherwise open an issue);

**Comment by pbertsch** [comment]
Didn't work on my iPhone Xr

**Comment by tsiareshchankau** [comment]
> Turns out when my phone was updated to 16.0.2, there was a Developer Mode flag on the device that was disabled. Once I enabled that everything started working
The flag is under Settings -> Privacy and Security -> Developer Mode

this ^

thanks @dkman94
