### ISSUE TITLE
xcode13.4.1 compile iOS 16.0.2

### ISSUE THREAD

**Issue by taojeff** [filsv/iOSDeviceSupport#151]
I found a problem today. When I used Xcode13.4.1 to compile iOS16.0.2 system for iPhone 8Plus, I found that the compilation was successful, but the mobile APP started very slow and slow. When I used iPhone 11 with the same system to compile, I was directly prompted that the version of the phone was too high to compile

**Comment by LiuLewis1989** [comment]
aaaa
