### ISSUE TITLE
Support for iOS 16.1

### ISSUE THREAD

**Issue by moses-mbaga** [filsv/iOSDeviceSupport#155]
Can you please add the Device Support files for iOS 16.1

**Comment by chmiiller** [comment]
as @jinfagang said:
you can download it from [here](https://github.com/iGhibli/iOS-DeviceSupport/blob/master/DeviceSupport/16.1%20(FromXCode_14.1(14B5024h)).zip)

**Comment by fbaptista** [comment]
Hello. I created a pull request with latest images: https://github.com/filsv/iOSDeviceSupport/pull/160
Otherwise just pull them from the fork at: https://github.com/apptim/iPhoneOSDeviceSupport

**Comment by JinjunHan** [comment]
Hello, you can download from here. [https://github.com/JinjunHan/iOSDeviceSupport](https://github.com/JinjunHan/iOSDeviceSupport)

**Comment by filsv** [comment]
@moses-mbaga @chmiiller @fbaptista @JinjunHan Please use this link: [Download](https://github.com/filsv/iOSDeviceSupport/raw/master/16.1.zip).
