### ISSUE TITLE
Support for iOS 16.3.1

### ISSUE THREAD

**Issue by Azeem-dash** [filsv/iOSDeviceSupport#161]
any iOS support files for the newer iOS version

**Comment by fbaptista** [comment]
Dear, check our fork at: https://github.com/apptim/iPhoneOSDeviceSupport

**Comment by Azeem-dash** [comment]
> Dear, check our fork at: https://github.com/apptim/iPhoneOSDeviceSupport

yeah! I already check this but 16.3 is not working for me I need 16.3.1 because today I update my device to 16.3.1

**Comment by fbaptista** [comment]
> 

Are you sure that image 16.3 does not work on 16.3.1? Do you have any evidence ?

**Comment by thuhuwei** [comment]
Same problem for me. I add 16.3 but it's not working.

**Comment by thuhuwei** [comment]
Maybe because upgrading to 16.3.1 makes the developer mode is off.

**Comment by fbaptista** [comment]
Yes, that should be the reason. I tried 16.3 on 16.3.1 and it's working.

**Comment by jeancsanchez** [comment]
@fbaptista  I recently upgraded to 16.3.1 and the image 16.3 worked for me. I just closed and reopened Xcode again. 
Try restarting your devices...

**Comment by JinjunHan** [comment]
Hello, you can download from here. [https://github.com/JinjunHan/iOSDeviceSupport](https://github.com/JinjunHan/iOSDeviceSupport)

**Comment by marcosabb** [comment]
> Hello, you can download from here. https://github.com/JinjunHan/iOSDeviceSupport

Thank you @JinjunHan, it worked in 16.4 iOS version. 🥳

**Comment by nachocruel** [comment]
In my case it was necessary to enable "developer mode" (setting/privacy and security). Then the version 16.3 worked in a 16.3.1.
