### ISSUE TITLE
Support for iOS 16.4.1

### ISSUE THREAD

**Issue by M1Dr05** [filsv/iOSDeviceSupport#164]
any iOS support files for the newer iOS version ???

**Comment by filsv** [comment]
@M1Dr05 Hi, have you tried to rename "16.4" folder to "16.4.1" ? Simply copy-paste 16.4 Folder, and rename it to "16.4.1". 
Let me know if not worked.

**Comment by shahnawazhussain125** [comment]
I rename the folder "16.4" to "16.4.1" and it is working for me.

**Comment by filsv** [comment]
@shahnawazhussain125 Glad to help ;)

**Comment by armanivers** [comment]
this didn't work for me sadly, I renamed the folder from 16.4 to 16.4.1 but it still fails to prepare the device for development after the app was built, any suggestions?
