### ISSUE TITLE
Support for iOS 16.5

### ISSUE THREAD

**Issue by Shahidbangash** [filsv/iOSDeviceSupport#165]
Hi

Please add IOS support files for the newer iOS version (16.5).

**Comment by Sadow32** [comment]
Same issue here

**Comment by fadecutmike** [comment]
+1

**Comment by Walker023** [comment]
+1

**Comment by bikee1235** [comment]
+1

**Comment by Jamal-ReachFirst** [comment]
+1

**Comment by LorinRain** [comment]
[Download 16.4](https://github.com/filsv/iOSDeviceSupport/raw/master/16.4.zip) and rename it to "16.5"

**Comment by jessecoding** [comment]
> [Download 16.4](https://github.com/filsv/iOSDeviceSupport/raw/master/16.4.zip) and rename it to "16.5"

work ok!

**Comment by Jamal-ReachFirst** [comment]
> > [Download 16.4](https://github.com/filsv/iOSDeviceSupport/raw/master/16.4.zip) and rename it to "16.5"
> 
> work ok!

same here, works for me

**Comment by Shahidbangash** [comment]
> [Download 16.4](https://github.com/filsv/iOSDeviceSupport/raw/master/16.4.zip) and rename it to "16.5"

it worked here
