### ISSUE TITLE
iOS 16.5 zip contains only iOS subfolder 16.4

### ISSUE THREAD

**Issue by marcantoineg** [filsv/iOSDeviceSupport#168]
As the title says, the subfolder inside the `16.5.zip` file is named 16.4. It works as intended (as far as I know) but it's a bit misleading. Feel free to close this issue if this is intended! 😄 

The file in question:
https://github.com/filsv/iOSDeviceSupport/blob/master/16.5.zip

**Comment by Hitek55** [comment]
the files inside assume version 16.4, i.e. 16.4 and the new 16.5 are now duplicates of each other, fix this please

**Comment by JesusLuvsYooh** [comment]
ahah was just about to report this too!

**Comment by wfs498121294** [comment]
ahah was just about to report this too!

**Comment by sashakid** [comment]
Doesn't work for me, neither 16.4 as it is, nor renaming 16.4 to 16.5. I have Xcode 14.1 with error `Command CodeSign failed with a nonzero exit code`trying to run app on device. :-(

**Comment by wfs498121294** [comment]
> 

rename 16.4 to 16.5, it`s work

**Comment by filsv** [comment]
Guys please check now, should be okay.

**Comment by joshuabeeler** [comment]
> rename 16.4 to 16.5, it`s work

That worked for me, too!
