### ISSUE TITLE
iOS 17.0 Beta Device Support Files

### ISSUE THREAD

**Issue by SPrasadT** [filsv/iOSDeviceSupport#169]
Hi,

Any chance we can get iOS 17.0 device support files, on installing Xcode beta 15, I couldn't find the device support files for iOS 17 beta.

Thanks.

**Comment by filsv** [comment]
@SPrasadT I've tried as well, not available yet, will add as soon as it will be available.

**Comment by marcosabb** [comment]
@filsv still no available?

**Comment by fantasticrahulrai** [comment]
I also badly need iOS 17, please try to add it as soon as possible

**Comment by lycfr** [comment]
I also badly need iOS 17, please try to add it as soon as possible

**Comment by JGameMaker92** [comment]
I really need those iOS 17 Beta Support files as well. Unable to install XCode 15 Beta and can’t deploy to my iPhone anymore

**Comment by SPrasadT** [comment]
If there is no device support files, how will go-ios, tidevice, or even idevice libs work? scary that many of the CLI based operations will not work for iOS 17.

**Comment by felipecastrosales** [comment]
@filsv any expectation in this?

**Comment by laiyierjiangsu** [comment]
any expectation in this?

**Comment by filsv** [comment]
@laiyierjiangsu @SeanRobinson159 @fantasticrahulrai @SPrasadT Guys please try this workaround and let me know if it's worked (Please note you need Xcode 14+ to get it work): 

> [!WARNING]
> <strong>⚠️ iOS 17+ Workaround (Xcode 14+ required):</strong><br>
> In the terminal run:
> </br>
> ```shell
> defaults write com.apple.dt.Xcode DVTEnableCoreDevice enabled
> ```
> </br>
> Then restart Xcode 14 the iOS 17 device will show up in Xcode like below and you can run and debug the app as usual. (You may need to go to Devices and Simulators to pair/trust the device)
>
> I have Xcode 15 beta installed alongside Xcode 14, I'm not sure if that's required or not.
> - [Based on this](https://forums.developer.apple.com/forums/thread/730947?answerId=758061022#758061022)
