### ISSUE TITLE
Add new Disk Image for latest iOS Version for , 16.5.1

### ISSUE THREAD

**Issue by jakirkhanNEw** [filsv/iOSDeviceSupport#170]
Please add the new disk image for latest version.

**Comment by bllizard22** [comment]
Do you mean `/DeviceSupport/16.5.1?`
You can use 16.5 instead. I have 16.5.1 on the device and that one work fine

**Comment by mostasim** [comment]
> Do you mean `/DeviceSupport/16.5.1`? You can use 16.5 instead. I have 16.5.1 on the device and that one works fine

Yes, That's work for me

**Comment by filsv** [comment]
@bllizard22 Thanks for this workaround.
