### ISSUE TITLE
iOS 16.5.1(c) 

### ISSUE THREAD

**Issue by G-Singularity** [filsv/iOSDeviceSupport#171]
iOS 16.5.1(c)  with the support 16.5.1， can build， but can't run or debug.  Any new Device Support  for iOS 16.5.1(c) ?

**Comment by michelorth** [comment]
I also have this problem

**Comment by shahzadmajeed** [comment]
+1 for this please

**Comment by filsv** [comment]
@G-Singularity @michelorth @shahzadmajeed Guys please try this workaround and let me know if it's worked for you:

Just use 16.5 and rename the folder:
```- To get iOS 16.(version) [example iOS 16.5.1] - just rename a folder.
- Like this: 16.5 ~> 16.5.1;
```
