### ISSUE TITLE
Whee should the __MACOSX folder be placed?

### ISSUE THREAD

**Issue by marlon-sousa** [filsv/iOSDeviceSupport#173]
Hello,

Before you ask me to look at the readme, please let me explain why I am asking this.

I am a blind developer, trying to deploy an app on my iPhone SE third generation from XCode 13.2.1.

As expected, it does not work, so I have found this project.

In the readme, there is a image showing folder hierarchy that my screen reader could not recognize.

I see two folders at the root of the zipped file:

16.5 and __MACOSX.

I placed the 16.5 folder at the /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/ and my iphone now appears on the view / destinations menu (it was dimmed before). But the build is still dimmed, and developer mode does not appear on the phone.

In Windows - devices and simulators the device is listed, but an error saying device failed to be prepared to run or something alike is shown.

Having placed the 16.5 folder in the specified place, the only thing which could be missing was the __MACOSX folder delivered in the zipped file. I would like to know where I should place it.

**Comment by filsv** [comment]
@marlon-sousa It would be an honor to help you. 
Here are the hierarchy:
`Xcode-beta.app
├── Contents
│   ├── _CodeSignature
│   ├── Applications
│   ├── Developer
│   │   ├── Applications
│   │   ├── Library
│   │   ├── Makefiles
│   │   ├── Platforms
│   │   │   ├── AppleTVOS.platform
│   │   │   ├── AppleTVSimulator.platform
│   │   │   ├── iPhoneOS.platform
│   │   │   │   ├── _CodeSignature
│   │   │   │   ├── Developer
│   │   │   │   ├── DeviceSupport
│   │   │   │   │   ├── 8.0
│   │   │   │   │   ├── 8.1
│   │   │   │   │   ├── 8.2
│   │   │   │   │   ├── 8.3
│   │   │   │   │   ├── 8.4
│   │   │   │   │   ├── 9.0
│   │   │   │   │   ├── 9.1
│   │   │   │   │   ├── 9.2
│   │   │   │   │   ├── 9.3
│   │   │   │   │   ├── 10.0
│   │   │   │   │   ├── 10.1
│   │   │   │   │   ├── 10.2
│   │   │   │   │   ├── 10.3
│   │   │   │   │   ├── 11.0
│   │   │   │   │   ├── 11.1
│   │   │   │   │   ├── 11.2
│   │   │   │   │   ├── 11.3
│   │   │   │   │   ├── 11.4
│   │   │   │   │   ├── 12.0
│   │   │   │   │   ├── 12.1
│   │   │   │   │   ├── 12.2
│   │   │   │   │   ├── 12.3
│   │   │   │   │   ├── 13.0
│   │   │   │   │   ├── icon.icns
│   │   │   │   │   ├── info.plist
│   │   │   │   │   ├── Library
│   │   │   │   │   ├── user
│   │   │   ├── MacOSX.platform
│   │   │   ├── WatchOS.platform
│   │   │   ├── WatchSimulator.platform
│   │   ├── Toolchains
│   │   ├── Tools
│   │   ├── usr
│   ├── Frameworks`

And you should put relevant version at this path: 
`Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/HERE_YOU_PUT_A_VERSION_FOLDER`
You your case it will be: `Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/16.5`.

Please let me know if it helped you.

By the way, thanks for writing, i'll add text representation of the folder hierarchy on Readme.
