### ISSUE TITLE
iOS 17 beta support??

### ISSUE THREAD

**Issue by chloekorzh** [filsv/iOSDeviceSupport#174]

**Comment by fareessyed-cred** [comment]
+1

**Comment by kaiserabliz** [comment]
+1

**Comment by zhaocw8888** [comment]
+1

**Comment by yuriy3122** [comment]
+1

**Comment by omarchaabounitn** [comment]
https://developer.apple.com/forums/thread/730947

**Comment by gbabucs** [comment]
+1

**Comment by kaiserabliz** [comment]
+1

**Comment by idanhauser** [comment]
+1 will be ?

**Comment by ghostwolf90** [comment]
+1

**Comment by CMLCNL** [comment]
+1

**Comment by filsv** [comment]
@gbabucs @ghostwolf90 @kaiserabliz @charleszhao888888 @yuriy3122 Guys please try this workaround and let me know if it's worked (Please note you need Xcode 14+ to get it work): 

> [!WARNING]
> <strong>⚠️ iOS 17+ Workaround (Xcode 14+ required):</strong><br>
> In the terminal run:
> </br>
> ```shell
> defaults write com.apple.dt.Xcode DVTEnableCoreDevice enabled
> ```
> </br>
> Then restart Xcode 14 the iOS 17 device will show up in Xcode like below and you can run and debug the app as usual. (You may need to go to Devices and Simulators to pair/trust the device)
>
> I have Xcode 15 beta installed alongside Xcode 14, I'm not sure if that's required or not.
> - [Based on this](https://forums.developer.apple.com/forums/thread/730947?answerId=758061022#758061022)
