### ISSUE TITLE
cannot run version 16.5.2 on Mac m1 mini and Xcode 14.2

### ISSUE THREAD

**Issue by nguyendai-reddevil** [filsv/iOSDeviceSupport#175]

**Comment by filsv** [comment]
@nguyendai-reddevil Please try to use 16.5 and rename the folder, follow this instructions: 

Just use [16.5](https://github.com/filsv/iOSDeviceSupport/raw/master/16.5.zip) and rename the folder:
```- To get iOS 16.(version) [example iOS 16.5.1] - just rename a folder.
- Like this: 16.5 ~> 16.5.1;
```
