### ISSUE TITLE
ios 16.6 support available?

### ISSUE THREAD

**Issue by abhishek190** [filsv/iOSDeviceSupport#176]

**Comment by immex-tech** [comment]
Need this one badly.

**Comment by fbaptista** [comment]
you can download from : https://github.com/apptim/iPhoneOSDeviceSupport/blob/master/16.6.zip

**Comment by shubhamk840** [comment]
Thanks @fbaptista

**Comment by abhishek190** [comment]
Thanks @fbaptista
