### ISSUE TITLE
ios 16.6 available please

### ISSUE THREAD

**Issue by yann-yvan** [filsv/iOSDeviceSupport#177]

**Comment by felipecastrosales** [comment]
I'm needing this.

**Comment by 20chad16** [comment]
Any update on this?

**Comment by wb-s** [comment]
How are these being developed ahead of releases

**Comment by hadyhelal** [comment]
In case any one has more than Xcode version in his mac you have to make sure to copy files to the right location based on the required Xcode you will run from

**Comment by filsv** [comment]
@yann-yvan @felipecastrosales @20chad16 @wb-s @hadyhelal Guys 16.6 [available here](https://github.com/filsv/iOSDeviceSupport/raw/master/16.6.zip).
