### ISSUE TITLE
Official iOS 17 , Xcode 15 ?

### ISSUE THREAD

**Issue by iosMaher** [filsv/iOSDeviceSupport#178]

**Comment by RakhmatovBeymamat** [comment]
+1

**Comment by Coderxle** [comment]
+1

**Comment by Coderxle** [comment]
And xCode 15 DeviceSupport does not include iOS 17

**Comment by fampaySiddharth** [comment]
+1

**Comment by Mehul1437** [comment]
+1

**Comment by 3257** [comment]
+1

**Comment by duduwei** [comment]
+1

**Comment by Choyeongdeok** [comment]
+1

**Comment by gulalicelik** [comment]
+1

**Comment by ayoubm** [comment]
+1

**Comment by AkshayND** [comment]
+1

**Comment by favazHF** [comment]
+1

**Comment by fbaptista** [comment]
Hello everybody. 
iOS 17 has a quite different way to communicate with the device. You will not be able to mount devImages like before. 
Check this repo for supporting ios17 image mount using python: https://github.com/doronz88/DeveloperDiskImage
