### ISSUE TITLE
iOS 16.7

### ISSUE THREAD

**Issue by aman-codes-1** [filsv/iOSDeviceSupport#179]

**Comment by avfridrik** [comment]
16.7.1?

**Comment by filsv** [comment]
@aman-codes-1 @avfridrik Guys please try to use this workaround:

- To get iOS 16.(version) [example iOS 16.7] works with iOS 16.0, just rename a folder.
- Rename like this: [16.5](https://github.com/filsv/iOSDeviceSupport/raw/master/16.5.zip) ~> "16.7"; or in case of @avfridrik do "[16.5](https://github.com/filsv/iOSDeviceSupport/raw/master/16.5.zip)" -> "16.7.1" (if it not works try to use [16.6](https://github.com/filsv/iOSDeviceSupport/raw/master/16.6.zip) and rename it)
