### ISSUE TITLE
Version 15.8

### ISSUE THREAD

**Issue by diegocidm4** [filsv/iOSDeviceSupport#182]
My iPhone has just been updated to version 15.8 and now I can't use it with XCode because I can't find the package for this version.
Is there any way to solve it?

**Comment by aavuzb** [comment]
Now, I also have this issue:(

**Comment by FunkyLau** [comment]
+1

**Comment by 1finger** [comment]
+

**Comment by diegocidm4** [comment]
I was finally able to solve it by going back to a previous version of iOS. Specifically 15.7.9

**Comment by aavuzb** [comment]
How did you go back? Please teach us. I am going to do like you

**Comment by nirav-resideo** [comment]
Can not downgrade iPhones as Apple has stop signing ipsw for iPhones with 15.7.9.

**Comment by nirav-resideo** [comment]
> I was finally able to solve it by going back to a previous version of iOS. Specifically 15.7.9


Can not downgrade iPhones as Apple has stop signing ipsw for iPhones with 15.7.9.

**Comment by diegocidm4** [comment]
I have used this tutorial.
https://www.applesfera.com/tutoriales/como-saber-que-versiones-ios-siguen-firmadas-apple-para-descargarlas-formato-ipsw

Version 15.7.9 is still signed by Apple.

**Comment by iamvijay7** [comment]
I am seeing this

![Screenshot 2023-11-02 at 4 04 34 PM](https://github.com/filsv/iOSDeviceSupport/assets/46953373/23e23aa8-c07d-410c-bd6f-d85c2d2332b9)

**Comment by diegocidm4** [comment]
Indeed today it is no longer available. I did it on Tuesday and it was signed.

**Comment by nirav-resideo** [comment]
Apple stopped it in last 2 days somewhere. I have updated to MacOS 12.7.1 (21G920) and now my iPhone 6s iOS 15.8 is compatible with no issues (I have also pasted 16.4 DeviceSupport in Xcode but I think OS update did make it work).

**Comment by ryantriyatna** [comment]
+1, any workaround about this ?

**Comment by 1finger** [comment]
Who creating those files? or how they appears here? Or possible to made by itself?

**Comment by abdoerrahiem** [comment]
What is the status guys? I need IOS 15.8

**Comment by brand17** [comment]
+1

**Comment by brand17** [comment]
> Apple stopped it in last 2 days somewhere. I have updated to MacOS 12.7.1 (21G920) and now my iPhone 6s iOS 15.8 is compatible with no issues (I have also pasted 16.4 DeviceSupport in Xcode but I think OS update did make it work).

Which XCode version are you using? XCode 14.3 is not supported by Monterray. XCode 14.1 and 14.2 raise the same error - Failed to prepare the device for development even when I copied 16.4 DeviceSupport from https://github.com/filsv/iOSDeviceSupport. Tried to reset Iphone/Mac/Usb - nothing works.

**Comment by thangldvn** [comment]
+1

**Comment by thangldvn** [comment]
I have found the solution from https://github.com/master131/iFakeLocation/issues/162#issuecomment-1793576376 : Use image 15.5. Rename the folder from 15.5 -> 15.8.

**Comment by 1finger** [comment]
> I have found the solution from [master131/iFakeLocation#162 (comment)](https://github.com/master131/iFakeLocation/issues/162#issuecomment-1793576376) : Use image 15.5. Rename the folder from 15.5 -> 15.8.

I tried change from, 15.7 change but not from 15.5 - thank you.

**Comment by AbdullahIqbal** [comment]
> > I have found the solution from [master131/iFakeLocation#162 (comment)](https://github.com/master131/iFakeLocation/issues/162#issuecomment-1793576376) : Use image 15.5. Rename the folder from 15.5 -> 15.8.
> 
> I tried change from, 15.7 change but not from 15.5 - thank you.

I tried this but did not worked. Any solution

**Comment by 1finger** [comment]
> > > I have found the solution from [master131/iFakeLocation#162 (comment)](https://github.com/master131/iFakeLocation/issues/162#issuecomment-1793576376) : Use image 15.5. Rename the folder from 15.5 -> 15.8.
> > 
> > 
> > I tried change from, 15.7 change but not from 15.5 - thank you.
> 
> I tried this but did not worked. Any solution

try restart maybe and computer and device

**Comment by gauravneosoft19** [comment]
Any news on the 15.8 update? I'm having trouble getting it to run. Tried changing folder names and restarting both my MacBook and iPhone, but no luck. Any ideas?

**Comment by Vendrel** [comment]
My eyes just started to glow in joy (not as a Goa'uld's) when Is saw the huge library of runtimes but as 15.8 is missing, unfortunately anything I develop stays in Xcode, never gets out onto a device of mine. 

All hope is lost now. But – rhetorical question – what if I buy the newest models then Apple updates their iOS but forgets to make the matching runtime for it?

**Comment by Haisea** [comment]
15.7 -> 15.8 not work
15.5-> 15.8  works

**Comment by iOS-Kel** [comment]
copy 15.5 and rename 15.8

**Comment by fatbuddy** [comment]
> I have found the solution from [master131/iFakeLocation#162 (comment)](https://github.com/master131/iFakeLocation/issues/162#issuecomment-1793576376) : Use image 15.5. Rename the folder from 15.5 -> 15.8.

the copy method works to me, thanks a lot!

**Comment by filsv** [comment]
Thanks a lot to all for help! @fatbuddy @FunkyLau @Haisea @Vendrel @iOS-Kel , closing this issue.

**Comment by Aniruddha22Gupta** [comment]
does this help **Iphone is busy: Making Iphone ready for development?** It takes forever to complete to check. Please help me to clear both the issues.
