### ISSUE TITLE
iOS 17

### ISSUE THREAD

**Issue by anitaspieker** [filsv/iOSDeviceSupport#183]

**Comment by HARSHVDARJI** [comment]
same here

**Comment by filsv** [comment]
@anitaspieker @HARSHVDARJI Guys please try this workaround and let me know if it's worked (Please note you need Xcode 14+ to get it work): 

> [!WARNING]
> <strong>⚠️ iOS 17+ Workaround (Xcode 14+ required):</strong><br>
> In the terminal run:
> </br>
> ```shell
> defaults write com.apple.dt.Xcode DVTEnableCoreDevice enabled
> ```
> </br>
> Then restart Xcode 14 the iOS 17 device will show up in Xcode like below and you can run and debug the app as usual. (You may need to go to Devices and Simulators to pair/trust the device)
>
> I have Xcode 15 beta installed alongside Xcode 14, I'm not sure if that's required or not.
> - [Based on this](https://forums.developer.apple.com/forums/thread/730947?answerId=758061022#758061022)
