### ISSUE TITLE
iOS 16.7.2, please!

### ISSUE THREAD

**Issue by renjunok** [filsv/iOSDeviceSupport#184]

**Comment by filsv** [comment]
@renjunok Please try to use [16.6](https://github.com/filsv/iOSDeviceSupport/raw/master/16.6.zip) instead, just rename the folder following this instructions:

- To get iOS 16.(version) [example iOS 16.7.2] works with iOS 16.0, just rename a folder.
- Like this: 13.6 ~> 16.7.2;
