### ISSUE TITLE
I need 17

### ISSUE THREAD

**Issue by lhhboy** [filsv/iOSDeviceSupport#185]

**Comment by HARSHVDARJI** [comment]
same here

**Comment by zhuyongbo100** [comment]
need ios 17 too

**Comment by yusakufujita** [comment]
need ios 17.2 too
please

**Comment by linjunjun1** [comment]
https://github.com/filsv/iOSDeviceSupport/assets/16476048/b2840ce1-c096-4fb8-b9df-03a4781aab25

**Comment by VHPFchefe** [comment]
me too

**Comment by Azeem00786** [comment]
me too, or any other solution except xcode 15 download.

**Comment by filsv** [comment]
@linjunjun1 @SeongwoonHong @HARSHVDARJI @zhuyongbo100 @lhhboy Guys please try this workaround and let me know if it's worked (Please note you need Xcode 14+ to get it work): 

> [!WARNING]
> <strong>⚠️ iOS 17+ Workaround (Xcode 14+ required):</strong><br>
> In the terminal run:
> </br>
> ```shell
> defaults write com.apple.dt.Xcode DVTEnableCoreDevice enabled
> ```
> </br>
> Then restart Xcode 14 the iOS 17 device will show up in Xcode like below and you can run and debug the app as usual. (You may need to go to Devices and Simulators to pair/trust the device)
>
> I have Xcode 15 beta installed alongside Xcode 14, I'm not sure if that's required or not.
> - [Based on this](https://forums.developer.apple.com/forums/thread/730947?answerId=758061022#758061022)

**Comment by joaquim-rovira** [comment]
This workaround does not work for me.  I have iMac OS Monterrey 12.7.5 (latest version supported by my iMac late 2015), Xcode 14.2 (latest supported by Monterrey) and iOS 17.5.1

**Comment by AppiChudilko** [comment]
> This workaround does not work for me. I have iMac OS Monterrey 12.7.5 (latest version supported by my iMac late 2015), Xcode 14.2 (latest supported by Monterrey) and iOS 17.5.1

Same, who can send files?
