### ISSUE TITLE
Cant upload app to a 15.5 device. The project is from unity to xcode

### ISSUE THREAD

**Issue by TilenG67** [filsv/iOSDeviceSupport#186]
Ive got a unity project and its been exported to xcode so i can upload it to iphone. the iphone has ios 15.5 and ive put in the files but i cannot select ios 15.5 in xcode. any suggestion? thanks

**Comment by filsv** [comment]
@TilenG67 Can you please attach a screenshot of what you are seeing at iOS version picker? (eg. [Here](![image](https://github.com/filsv/iOSDeviceSupport/assets/13712013/a2de38c6-0ba7-410d-8a61-854157716a85)))
